language: node.js
node_js:
  - "12.16.3"
sudo: required
dist: trusty

addons:
  chrome: stable

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - yarn build --prod --base-href $base_href


##services:
##  - docker
#
#before_script:
#  - export CHROME_BIN=/usr/bin/google-chrome
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start
#  - sudo apt-get update
#  - sudo apt-get install -y libappindicator1 fonts-liberation
#  - wget https://dl.google.com/linux/direct/google-chrome-stable-current_amd64.deb
#  - sudo dpkg -i google-chrome*.deb
#
#script:
#  #  - docker run -e CI=true repsteinky/lukuthemad npm run test
#  - ng test --watch false -cc
#  - npm run e2e
#  - ng build -bh "https://github.com/RossEpsteinKY/LukuTheMadWebsite.git"
#
#deploy:
#  provider: elasticbeanstalk
#  region: "us-east-2"
#  app: "LukuWebsite"
#  env: "LukuSiteEnv"
#  bucket_name: "elasticbeanstalk-us-east-2-907593648697"
#  bucket_path: "lukuwebsitebucket"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY

deploy:
  provider: s3
  region: "us-east-2"
  app: "LukuWebsite"
  env: "LukuSiteEnv"
  bucket_name: "lukuwebsitebucket"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  skip_cleanup: true
  acl: public_read

